# Generated by Django 4.1.7 on 2023-02-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_topic_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='topic',
        ),
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
