# Generated by Django 4.1.7 on 2023-02-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_remove_recipe_calories_remove_recipe_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Directions',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
