# Generated by Django 4.1.7 on 2023-02-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_recipe_directions_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Directions',
            new_name='directions',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
