# Generated by Django 4.1.5 on 2023-02-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followingandfollower',
            unique_together={('follower', 'followed')},
        ),
    ]
