# Generated by Django 4.1.5 on 2023-02-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_followingandfollower_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followingandfollower',
            old_name='follower',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='followingandfollower',
            old_name='followed',
            new_name='user_follower',
        ),
        migrations.AlterUniqueTogether(
            name='followingandfollower',
            unique_together=set(),
        ),
    ]
