# Generated by Django 4.1.5 on 2023-02-13 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_follower_followingandfollower_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingandfollower',
            name='user_follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
