# Generated by Django 4.1.5 on 2023-02-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_followingandfollower_user_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followingandfollower',
            old_name='user',
            new_name='user_following',
        ),
    ]
