# Generated by Django 4.1.5 on 2023-02-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_user_followingandfollower_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followingandfollower',
            old_name='user_following',
            new_name='user',
        ),
    ]
